<a href="https://colab.research.google.com/github/sanskar240/TensorFlow-Deep-Learning-stuff/blob/main/tensorflow__00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
#creating tensors with tf constant
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
#creating a vector

vector = tf.constant([10,10])
vector



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#creating a matrix

matrix = tf.constant([[10,7],[7,10]])

matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix 
another_matrix = tf.constant([[10.,7.],[3.,2.]],dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]]])
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
Scalar:a single **number**
Vector:number and direction
Matrix:a 2d array of numbers
Tensor:n dimensional(where n can be any number) **bold text**