<a href="https://colab.research.google.com/github/sanskar240/TensorFlow-Deep-Learning-stuff/blob/main/tensorflow__00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf
print(tf.__version__)

2.8.0


In [8]:
#creating tensors with tf constant
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
scalar.ndim

0

In [ ]:
#creating a vector

vector = tf.constant([10,10])
vector



<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [12]:
vector.ndim

NameError: ignored

In [13]:
#creating a matrix

matrix = tf.constant([[10,7],[7,10]])

matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
matrix.ndim

2

In [15]:
#create another matrix 
another_matrix = tf.constant([[10.,7.],[3.,2.]],dtype = tf.float16)

another_matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.]], dtype=float16)>

In [16]:
another_matrix.ndim

2

In [17]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]]])
tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [18]:
tensor.ndim

3

What we've created so far:
Scalar:a single **number**
Vector:number and direction
Matrix:a 2d array of numbers
Tensor:n dimensional(where n can be any number) **bold text**

Creating tensors with tf.variables

In [20]:
#creating tensors with tf.variable()

changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [22]:
#changing value of variable tensor

changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Creating Random Tensors
Random Tensors are tensors of arbitrary size which contains random numbers

In [25]:
#Creating two random similar tensors
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape = (3,2))
random_1
random_2 = tf.random.Generator.from_seed(21)
random_2 = random_2.normal(shape = (4,2))
random_2




<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-1.322665  , -0.02279496],
       [-0.1383193 ,  0.44207528],
       [-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.85445154]], dtype=float32)>